query FetchPodcast($id: ID!) {
  podcast(itunesId: $id) {
    itunesId
    name
    creator
    description
    artworks {
      url
      size
      type
    }
    episodes {
      title
      file
      artworks {
        url
        size
        type
      }
    }
  }
}
