query FetchLibrary($ids: [ID]!) {
  podcasts(itunesIds: $ids) {
    itunesId
    name
    creator
    feed
    artworks {
      url
      size
      type
    }
    colors {
      name
      value
    }
  }
}
