query FetchEpisode($pId: ID!, $eId: ID!) {
  episode(podcastId: $pId, episodeId: $eId) {
    title
    file
    date
    id
    duration
    descr {
      short
      long
    }
    artworks {
      url
      size
      type
    }
  }
}
