query FetchPodcast($id: ID!) {
  podcast(itunesId: $id) {
    id
    name
    creator
    descr {
      short
      long
    }
    artworks {
      url
      size
      type
    }
    colors {
      name
      value
    }
    episodes {
      title
      file
      date
      duration
      id
    }
  }
}
