version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: echo $CACHE_KEY > _tmp_cache_key
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "_tmp_cache_key" }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ checksum "_tmp_cache_key" }}-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Move sourcemaps
          command: |
            rm public/*/*.map
            mkdir sentry
            mv public/*.map sentry
            mv .sentry-release sentry
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "_tmp_cache_key" }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            sudo apt install rsync
            rsync -avr public/ public/br --exclude="br" --exclude="gz" --ignore-existing
            rsync -avr public/ public/gz --exclude="br" --exclude="gz" --ignore-existing
            aws s3 sync public/ s3://yapp-frontend/ --exclude="gz/*" --exclude="br/*"
            aws s3 sync public/ s3://yapp-frontend/ --exclude="*" --include="gz/*" --content-encoding="gzip"
            aws s3 sync public/ s3://yapp-frontend/ --exclude="*" --include="br/*" --content-encoding="br"

  sentry:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Sentry CLI
          command: sudo npm install -g @sentry/cli --unsafe-perm
      - run:
          name: Create Sentry release
          command: |
            VERSION=$(cat sentry/.sentry-release)
            VERSION_INFO=$(sentry-cli releases info "$VERSION")
            if [[ "$VERSION_INFO" == *"No such release"* ]]; then 
              sentry-cli releases new -p "$SENTRY_PROJECT" "$VERSION"
              sentry-cli releases set-commits --auto "$VERSION"
              sentry-cli releases files "$VERSION" upload-sourcemaps ./sentry
              sentry-cli releases finalize "$VERSION"
            else
              echo "skip sentry release of $VERSION"
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - develop

  develop:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - sentry:
          requires:
            - build
          filters:
            branches:
              only: develop

  master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
