version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-${CACHE_VERSION}-{{ checksum "package.json" }}
            - v1-dependencies-${CACHE_VERSION}-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-${CACHE_VERSION}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: public

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            rsync -avr public/ public/br --exclude="br" --exclude="gz" --ignore-existing
            rsync -avr public/ public/gz --exclude="br" --exclude="gz" --ignore-existing
            aws s3 sync public/ s3://yapp-frontend/ --exclude="gz/*" --exclude="br/*"
            aws s3 sync public/ s3://yapp-frontend/ --exclude="*" --include="gz/*" --content-encoding="gzip"
            aws s3 sync public/ s3://yapp-frontend/ --exclude="*" --include="br/*" --content-encoding="br"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
